Update main.ts
Duplicate identifier 'enableProdMode'.

Breaks the build with Typescript :
Error: Typescript found the following errors:
  .../tmp/broccoli_type_script_compiler-input_base_path-jGoTJtyT.tmp/0/src/app/bower_components/vaadin-combo-box/test/angular2/main.ts (2, 51): Duplicate identifier 'enableProdMode'.
 .../tmp/broccoli_type_script_compiler-input_base_path-jGoTJtyT.tmp/0/src/app/bower_components/vaadin-combo-box/test/angular2/main.ts (4, 9): Duplicate identifier 'enableProdMode'.